version: '3.3'
services:
    nginx:
        build:
            context: ./images
            dockerfile: nginx
        container_name: lets-discuss-nginx
        ports:
            - '80:80'
        volumes:
            - './:/var/www'
            - './nginx:/etc/nginx/conf.d:rw'
        image: "nginx:latest"
        networks:
            - app_network
    php72:
        build:
            context: ./images
            dockerfile: php72
        container_name: php72
        working_dir: /var/www
        volumes:
            - './:/var/www'
        image: "php72_fpm:latest"
        networks:
            - app_network
    mysql:
        image: "mysql:5.7.22"
        container_name: mysql
        environment:
            MYSQL_DATABASE: letsdiscussDB
            MYSQL_USER: adminDB
            MYSQL_ROOT_PASSWORD: admin123
        ports:
            - '3306:3306'
        volumes:
            - 'dbdata:/var/lib/mysql/'
            - './mysql/my.cnf:/etc/mysql/my.cnf'
        networks:
            - app_network
networks:
    app_network:
        driver: bridge
volumes:
    dbdata: 
        driver: local